### ISSUE TITLE
Add/repair validations for attributes

### ISSUE THREAD

**Issue by graft** [mountetna/magma#126]
The validation system runs a number of different kinds of validation, one of which is attribute validation (`Magma::Validation::Attribute`, not to be confused with `Magma::Attribute::Validation`, although you will). Essentially, this will ensure that each attribute thinks the value being passed in is valid according to the requirements of the attribute (whatever they are). The corresponding attribute validation is performed by each attribute's validation class (e.g. `Magma::IntegerAttribute::Validation`), if these exist. Apparently, because of the way constants work, if they do not exist it will default (probably incorrectly) to `Magma::Attribute::Validation`.

This class is the sole place where the `match` parameter of the attribute is used (other than an obscure usage by the `matrix` attribute); it seems as if the usage of this parameter as written in `Magma::Attribute::Validation` is really only appropriate to string attributes (i.e., match against a regexp and match against an array of strings) and could (should) be renamed to `Magma::StringAttribute::Validation`.

The purpose of the match parameter on the attribute is to provide a way to lightly configure these attribute-level validations. A few of the attribute classes have their own custom validations, but there are some holes (notably, float/integer/date_time should have range validations on them).
In the future we'd also like to move these to a json column in the attributes table.

The work:
0) Rename `Magma::Attribute#match` to `validation`
1) Create validation classes for `IntegerAttribute`, `FloatAttribute`, `DateTimeAttribute` which use the `@validation` parameter to validate ranges for these values.
2) Move `Magma::Attribute::Validation` to `Magma::StringAttribute::Validation`
3) Investigate if other validations make sense for other types.

Lastly, once this is done:
4) Add a `validation` json column to populate the attribute.  Note that previously we used the ruby class to determine how the matcher works (i.e., Array vs. Regexp); this might be a bit confused in JSON, which has no Regexp type. While we might equivocate and try to make a JSON string pass as a regexp or some other nonsense, probably we should be more explicit. Conveniently, the `MatchAttribute` actually already defines a JSON format for holding a match configuration that works against a number of different types; we should probably re-use this here.

**Comment by alimi** [comment]
> 1. Create validation classes for IntegerAttribute, FloatAttribute, DateTimeAttribute which use the @match parameter to validate ranges for these values.

@graft should "use the `@match` parameter" be "use the `@validation` parameter" since `match` will be renamed to `validation` in step 0?

**Comment by alimi** [comment]
Will the new validation parameter still need to support procs like match currently does?

https://github.com/mountetna/magma/blob/d6764d31e6e64b9447f6480e6af58cf14c3db0e1/lib/magma/attribute.rb#L157-L159

**Comment by graft** [comment]
This is like going through a box of photos from middle school. The only use of Procs is in ipi for generating a Regexp:
`projects/ipi/models/rna_seq.rb:      match: Proc.new { IPI.match(:rna_seq_name) }`

So strictly speaking this behavior is not required, as we could substitute it with the equivalent regexp and achieve the same result. The procs in the ipi repo make use of a query of the database table to build the regexp; it might be nice to support validations that make use of queries to determine their result, but I think that can be determined downstream.

**Comment by alimi** [comment]
I'm a little confused on how matrix attributes work. Looking at the validation, it looks like matrices are arrays where every element is a number and they have the same length as the match option?

https://github.com/mountetna/magma/blob/b9ce3a1028847ece9239d841e5fe0236a0ee8024/lib/magma/attributes/matrix.rb#L9-L18

If that's true, then why is `match` here an array of strings?

https://github.com/mountetna/magma/blob/b9ce3a1028847ece9239d841e5fe0236a0ee8024/spec/labors/models/labor.rb#L15

**Comment by graft** [comment]
The `matrix` attribute holds a matrix of data across the model; it's actually more like a data frame, in that the rows and columns have names. The row names come from the identifier of the model, so that each record holds one row of the matrix as a vector (Array) of values. The column names depend on the attribute in question.

For example, in ipi, the `rna_seq` model has a matrix attribute `gene_tpm`. This holds a gene expression matrix - every sample has a gene expression value for each gene in the genome. So the column names of each row in the matrix are each gene in the genome (there are 60,000). This means each row must contain a vector of 60,000 values; the validation checks that this is the case. As for the column names, they are stored in the match parameter. This gets used to count the number of columns (the size of the match array) and also gets used to slice the matrix by column names.

In the labors example, the matrix is (apparently) one of monetary contributions from each of the cities in question to the completion of the labor in question (i guess they are sponsoring Hercules by paying for wagon wheels and spear hafts or something). Each row in the matrix has four values, one for each contributing city; the match contains the names of those cities as column names.

**Comment by alimi** [comment]
Gotcha, thanks for explaining!

Would it be worth documenting how some of the attributes work? A lot of them are pretty straightforward, but matrix was definitely a head scratcher 😅

**Comment by alimi** [comment]
@graft do we want to add any more validations? If not, I think we can close this issue.

**Comment by graft** [comment]
We can hope that Future Us will take care of it.
