### ISSUE TITLE
Remove net-http-persistent dependency in magma_client

### ISSUE THREAD

**Issue by coleshaw** [mountetna/magma#149]
Per mountetna/etna#45, I think we can remove the `net-http-persistent` dependency in `magma_client` and also rely on the standard library.

**Comment by graft** [comment]
The metis client has special behavior (a shell) that makes it require a
standalone client. I also wanted to avoid any dependencies so people could
just grab the script and go; the magma client has no such special behavior
and might hopefully be replaced with just Etna::Client.

**Comment by coleshaw** [comment]
Replaced Magma Client in Timur with Etna Client. Closing because there are no other uses of Magma Client, so this is no longer an issue.
