### ISSUE TITLE
 Support add_model

### ISSUE THREAD

**Issue by graft** [mountetna/magma#170]
The data graph starts off with a single model - we wish to be able to grow this graph by adding new models.

At first glance this is a simple proposition - we only need to specify the name of the new model, the migration will create the new table, and *finis*. However, Magma wishes the models in the graph to be connected, and moreover to be connected in a tree with reciprocal links. A new, empty model is an orphaned subgraph and cannot be allowed. This means that the new model must be added with a valid link to an existing model.

This makes the input requirements of the `add_model` action slightly more complex: we must specify a parent model that this model attaches to. Furthermore, we must specify the relationship: the parent may link back using the `child`, `collection` or `table` attributes. So let's say we require `model_name, parent_model_name, parent_link_type`. Since Magma prefers string record identifiers, we might also require they name the new model's `identifier`, unless `parent_link_type` is `table`.

Now we have several tasks to perform: we must insert a new row into the model table, two or three new  rows in the attributes table (one for the parent attribute in the new model, one for the link in the parent model, possibly one for the identifier in the new model). We must load the new model and attributes.
In our migration we must create a new table for the model and add the new columns for the parent and identifier attributes.

**Comment by alimi** [comment]
@graft could `parent_link_type` also be `parent` for [`Magma::ParentAttribute`](https://github.com/mountetna/magma/blob/9f6e2eab1216a4c0f6c2c959caaab7d538aab127/lib/magma/attributes/parent_attribute.rb)?

**Comment by alimi** [comment]
Ah, I think I see what needs to happen. After we add a new model, we'll add a `parent` attribute for it to point to `parent_model_name`. Then we'll add an attribute to the parent model based off of`parent_link_type`. Is that right?

**Comment by graft** [comment]
Hmm, it appears magma does not yet validate, but should, that each model must have a single parent attribute (unless it is the 'project' model, in which it must have no parent attribute), i.e. the data graph is a tree with the project model at the root. Then we can add a new model as you describe and the graph will remain valid (where parent_link_type is one of `child, table, collection`).

**Comment by graft** [comment]
The reciprocal link requirement currently just looks for any link attribute pointing in this direction - i think, properly, there should be "link_out" (i.e., has a foreign key) and "link_in" (i.e., does not have a foreign key) attributes, and the reciprocal link requirement should require one of each. So link_out would be `link, parent`, and link_in would be `child, collection, table`. In this case, `parent` having the foreign key, the other must be one of `child, collection, table`.

**Comment by alimi** [comment]
Do we also need to support dictionaries or can that wait til later?

**Comment by graft** [comment]
Setting a dictionary in add_model seems a bit strong, it should suffice to set it in some sort of `update_model` action (presumably after we rename the endpoint itself from `update_model` :roll_eyes: ) somewhere down the road. In the meanwhile the column exists and can always be hand-edited if need be.
