### ISSUE TITLE
Retrieval API seems to fail when fetching 200 records (on the last page?)

### ISSUE THREAD

**Issue by coleshaw** [mountetna/magma#187]
You can see this behaviour in the Timur Search page, but it seems like sometimes when you search for 200 records (on patient for example), Magma returns a 500 / Server Error. The Magma logs show:

```
ERROR:2020-07-16T07:49:23-07:00 f83xip Caught unspecified error
ERROR:2020-07-16T07:49:23-07:00 f83xip 865: NaN not allowed in JSON
ERROR:2020-07-16T07:49:23-07:00 f83xip /var/www/magma/lib/magma/server/retrieve.rb:117:in `to_json'
ERROR:2020-07-16T07:49:23-07:00 f83xip /var/www/magma/lib/magma/server/retrieve.rb:117:in `json_payload'
ERROR:2020-07-16T07:49:23-07:00 f83xip /var/www/magma/lib/magma/server/retrieve.rb:93:in `perform'
ERROR:2020-07-16T07:49:23-07:00 f83xip /var/www/magma/lib/magma/server/retrieve.rb:61:in `action'
```
Not sure if it's a specific data entry or model. I see the same behaviour locally, especially when navigating around (using the > and < to view different pages of the results ... seems to happen a lot on the last page, but not always).

In the Timur UI, the only indication is that the results don't appear (in current production Timur), because the Magma error response doesn't include the `errors` key in the JSON response, but in Dev Tools you can see the error.

**Comment by graft** [comment]
Could you post the request params sent to /retrieve when this happens?

**Comment by coleshaw** [comment]
request:

```
{"model_name":"patient","record_names":"all","attribute_names":"all","page":1,"page_size":200,"collapse_tables":true,"project_name":"ipi"}
```

response: `{"error": "Server error."}`

**Comment by graft** [comment]
I can do it with `e.retrieve(model_name: "patient", record_names: ["IPICRC119"], attribute_names: [ :ice_time ], collapse_tables: true, project_name: "ipi")`

**Comment by graft** [comment]
Then:
```
irb(main):002:0> Ipi::Patient.where(ipi_number: "IPICRC119").first.ice_time
=> NaN
```
:shrug:

**Comment by graft** [comment]
I remediated in console; I am not sure how you can set a NaN - perhaps updating the value with a string? Anyway closing this and writing up a new issue about the float attribute.
