### ISSUE TITLE
Cannot insert 'nil' into date_time attributes

### ISSUE THREAD

**Issue by graft** [mountetna/magma#202]
Trying to /update a `date_time` attribute with the value nil results in a 500, because:
https://github.com/mountetna/magma/blob/30d1b6b4509f9e782e1ae3ae4fb2251b5b7b0bbf/lib/magma/attributes/date_time_attribute.rb#L7-L9

which fails because `DateTime.parse` does not accept `nil`.

**Comment by coleshaw** [comment]
This looks like it has been fixed.
