### ISSUE TITLE
Add PHI features to Magma attributes

### ISSUE THREAD

**Issue by graft** [mountetna/magma#36]
Any attribute in Magma can be flagged as 'phi'. If this is the case, Magma will:

1) Return the data if the user has permission 'phi' for the project. 

2) Return a transformed version of the data if the user lacks permission 'phi' for the project.

The transformation should be consistent - the easiest way is to compute it using a hash of an associated identifier (e.g. a patient identifier). The 'phi' attribute should therefore both point to the identifier used for anonymizing and specify an anonymization strategy.

**Comment by graft** [comment]
Importantly, the /retrieve and /query endpoints must censor the data appropriately.  If the attribute is flagged 'restricted' (what Janus calls this flag), /query and /retrieve should both refuse to show that data to a user without the restricted permission.

How should the censoring operate?

1. Should you remove restricted attributes from the JSON template, or leave the template intact describing what the user can't see?

2. Should you remove all restricted data from the JSON document describing a record, or merely replace it with a censored value? If the latter, how is the censored value computed?

**Comment by jasondcater** [comment]
From previous conversations we should remove/censor information while leaving the metadata intact. i.e. show that the field is present but remove the data.

**Comment by graft** [comment]
This is being implemented using the 'restricted' project permission on Janus. As Magma treats it, a record can have a 'restricted' attribute, or an attribute can be flagged as 'restricted' in the model. If the former is 'true', only project members with restricted permission can see anything from that record. If the latter is 'true', only project members can see data from that attribute in any record.

**Comment by graft** [comment]
How should censoring be done? All three endpoints, /update, /retrieve and /query, can yield potentially restricted data. Each should be censored to ensure that data does not leak out.

Data is accessed from these endpoints in a variety of ways - for example, the retrieve endpoint can return tsv or json-formatted data, with slightly different queries posted. At the end of the day, however, all three endpoints use a Magma::Question, which takes a query in Magma's query language, builds a corresponding SQL query, and executes that. It would seem logical, then, to perform the censoring here, rather than separately in each endpoint, to ensure that data cannot escape in uncensored form.

In order to accomplish this the Question needs to be aware of the restricted permissions, which it currently is not. Each endpoint has to pass the restriction (@user.can_see_restricted?(@project_name)) in to the Question. The /retrieve and /update endpoints both do this via the Magma::Retrieval object, which must be modified accordingly.

Alternative strategies:

1) Censor data as it comes out. This might be difficult as the results of a query would have to be re-parsed to understand the context.

2) Modify input queries to censor the results, e.g. use the Magma::Retrieval to build the censorship rules separately in each endpoint (and do something else for the /query endpoint which does not use Magma::Retrieval). This seems brittle and might lead to divergent behavior or leaking of data if the endpoint is not written correctly.
