### ISSUE TITLE
RedCap loader

### ISSUE THREAD

**Issue by graft** [mountetna/magma#61]
There should be a Magma::RedcapLoader < Magma::Loader, which is responsible for taking in data from a Redcap API and shoveling it into some Magma records.

1. The loader should define some basic RedCap API interfacing methods/objects.

2. The loader must perform the transformation from whatever the Redcap data format is to the Magma data format.

How does the loader support this transformation? A couple of possibilities:

1) Project-specific loaders extend Magma::RedcapLoader
2) The API accepts a mapping in YAML/JSON format between Redcap data items and Magma model/attributes.

Ideally the loader does both (2) and (1).

**Comment by jasondcater** [comment]
API access requires admin access for a redcap instance (which can be provided by another admin).  One must enable the API module/widget (left side of the UI). Then you should be able to generate an API key.

**Comment by graft** [comment]
There is a Redcap client in magma-ipi, I will at some point move it here.
