### ISSUE TITLE
Hot editing of models

### ISSUE THREAD

**Issue by graft** [mountetna/magma#99]
Magma models are fairly rigid data structures at this point - they are defined in a ruby class, which must be updated by creating a new branch for the project repo, editing the appropriate model file and updating an attribute, creating a pull request, deploying it to staging, etc. This is a very slow process.

Changes that add or remove attributes or introduce new models require writing a database migration. These changes might be more substantial and it might be important to do them by hand. Still, we might wish for tooling to make this process easy for us.

However, the other case, of changes to the models that do NOT require a migration, but merely change the description, match, etc., of an attribute do NOT need to live in the model. While the model might represent a sensible default, we can make these attributes user-accessible by moving them into a database.

Exposing these (especially the attribute.match, which performs validation) allows users (or at least superusers) to more directly shape usage of their models, for example by directly inputting and updating their preferred identifier pattern; it also reduces turnaround time on updating models and doesn't require a pull request/deploy cycle for silly changes like adding a text option to an array.

To make this change:
1. Add a base Attribute model, with project_name, model_name, attribute_name, and the modifiable attribute fields defined in the template: desc, display_name, match, format_hint. Anything touching the actual model table could not be changed, of course, like indexes, attribute name, type, etc.

2. Update the Magma::Model.json_template function so that it draws from the database for attribute data or uses the Magma::Attribute definition as a default.

**Comment by graft** [comment]
It seems like this issue could be implemented untouched on the road to #104. If we wanted to make it smaller we might slowly phase in the availability of columns in the attribute table (e.g., start with just 'description').

Some notes:

- 1 & 2 described above don't offer any way to update the attribute table. This probably requires the creation of an /update_model API as described in #104, which we might draw out later, but following THIS issue we would only be able to insert/update attribute definitions in the production console.
- Where should the attribute table go? There are two possibilities:
  1. Each project has its own attribute table (that is, `ipi`.`attributes`, the table 'attributes' in the schema 'ipi' in postgres). This allows us to keep the attribute table with each project, but requires separate migrations for each project if we want to update the attribute model.
  2. More likely: there is a single attribute table in some top-level partition shared by all projects. Magma maintains migrations to this table; `bin/migrate` runs these global migrations in addition to the project-specific migrations. There's some code supporting this in the fossilized branch [graft-add-load](/mountetna/magma/tree/graft-add-load) which was meant to fill out #84. In the future (#104) we might expect the project-specific migration code to fall away and only this global migration code remains.

**Comment by graft** [comment]
At the end, the attribute model should look like this:
```
    project_name - string, snake_case
    model_name - string, snake_case
    attribute_name - string, snake_case
    type - string, snake_case
    description - string, Details about the attribute's function
    display_name - string, A display-worthy version of the attribute name
    format_hint - string, brief help on how to make a valid entry
    validation - json, a configuration object specifying a validation
    restricted - boolean
    read_only - boolean
    hidden - boolean
 ```

**Comment by alimi** [comment]
@graft this should be closed by https://github.com/mountetna/magma/pull/132, right? I'm double checking to make sure I'm not missing anything 😁

**Comment by graft** [comment]
:crown:
